language: node_js
node_js:
  - "10"
script:
  - echo 'Installing dependencies'
  - npm install
  - sudo apt install zip unzip
  - echo 'Building project'
  - npm run build
  - echo 'Testing project'
  - npm run test