language: node_js
node_js:
  - "10"
cache: npm
script:
  - echo 'Installing dependencies'
  - npm install
  - sudo apt install zip unzip
  - echo 'Testing project'
  - npm run test

  after_success:
  - npm run deploy