language: node_js
node_js:
  - "10"
cache: npm
script:
  - echo 'Installing dependencies'
  - npm install
  - echo 'Testing project'
  - npm run test
  - echo 'Generating build folder for deployment'
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master